repos:
  # ruff for linting and formatting python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: cb8c523fd4835aba42af70f4cad5568db4df0b6c # frozen: v0.16.0
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-yaml
      - id: name-tests-test
        args: [--pytest-test-first]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 41e691678310dfd3833f7ab4e180ddb014310356 # frozen: v2.3.0
    hooks:
      - id: mypy
        additional_dependencies: [numpy]
  # yamlfmt for formatting YAML files
  - repo: https://github.com/google/yamlfmt
    rev: b5ca1890231d5e1e5181fef75a1be609d1e25029 # frozen: v0.21.0
    hooks:
      - id: yamlfmt
  # Codespell for spell checking
  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8 # frozen: v2.4.3
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        exclude_types: ["css", "html", "javascript", "json"]
  # Validate GitHub Actions workflow files
  - repo: https://github.com/mpalmer/action-validator
    rev: 76a805bbfcba3506d6cdb4bba1810ab504e0d72b # frozen: v0.9.0
    hooks:
      - id: action-validator
  # Security-focused GitHub Actions static analysis tool
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 067260dc5fe6ea86b7551bfd6f8b3ba4e6c93129 # frozen: v1.28.0
    hooks:
      - id: zizmor
        args: [--fix=safe] # enable safe fixes
