#!/usr/bin/env python

from collections import defaultdict
import pathlib

from babel.dates import get_month_names

# lark grammar path relative to this script
GRAMMAR_DIR_PATH = (
    pathlib.Path(__file__).parent.parent / "src" / "undate" / "converters" / "grammars"
)
# file that is generated by this script, in that directory
MONTH_GRAMMAR_FILE = GRAMMAR_DIR_PATH / "gregorian_multilang.lark"

# include month names in the following languages
languages = [
    "en",  # English
    "es",  # Spanish
    "fr",  # French
    "de",  # German
    "rw",  # Kinyarwanda
    "lg",  # Ganda
    "ti",  # Tigrinya
]

# warning to include at top of generated file
warning_text = """// WARNING: This file is auto-generated. DO NOT EDIT.
// To regenerate: uvx hatch run codegen:generate

"""


def main():
    # create a dictionary of lists to hold the names for each month
    all_month_names = defaultdict(list)

    for lang in languages:
        for width in ["wide", "abbreviated"]:
            for month_num, month_name in get_month_names(width, locale=lang).items():
                # some locales use a . on the shortened month; let's ignore that
                month_name = month_name.strip(".")
                # In some cases different languages have the same abbreviations;
                # in some cases, abbreviated and full are the same.
                # Only add if not already present, to avoid redundancy
                if month_name not in all_month_names[month_num]:
                    all_month_names[month_num].append(month_name)

    with MONTH_GRAMMAR_FILE.open("w") as outfile:
        outfile.write(warning_text)

        # for each numeric month, generate a rule with all variant names:
        # month_1:  "January" | "Jan"  ...
        for i, names in all_month_names.items():
            # combine all names in an OR string
            or_names = " | ".join(f'"{m}"' for m in names)
            outfile.write(f"month_{i}: {or_names}\n")

    print(
        f"Successfully regenerated {MONTH_GRAMMAR_FILE.relative_to(pathlib.Path.cwd())}"
    )
    print("If the file has changed, make sure to commit the new version.")


if __name__ == "__main__":
    main()
