name: Check style + docs + types

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Install package with check dependencies
        run: uv sync --group check

      - name: Run Ruff linter
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0
        with:
          args: "check --output-format=github"

      - name: Run Ruff formatter
        # NOTE: ruff format does not currently support github output format
        run: ruff format --check --diff  src tests
        # Check formatting even if the previous step failed
        if: always()

      # check docs build
      - name: Check that documentation builds with no errors or warnings
        run: uv run sphinx-build docs docs/_build --fail-on-warning

      # check types with mypy
      - name: Check types in python src directory; install needed types
        run: uv run mypy --install-types --non-interactive src

      # use treon to make sure that example notebooks run
      - name: Check jupyter notebooks with treon
        run: uv run treon
